export const CATEGORIES = [
  'Miscellaneous',
  'Ammo',
  'Arrows',
  'Bolts',
  'Construction Materials',
  'Construction Projects',
  'Cooking Ingredients',
  'Costumes',
  'Crafting Materials',
  'Familiars',
  'Farming Produce',
  'Fletching Materials',
  'Food and Drink',
  'Herblore Materials',
  'Hunting Equipment',
  'Hunting Produce',
  'Jewellery',
  'Mage Armour',
  'Mage Weapons',
  'Melee Armour- Low Level',
  'Melee Armour Mid-Level',
  'Melee Armour - High Level',
  'Melee Weapons - Low Level',
  'Melee Weapons - Mid Level',
  'Melee Weapons - High Level',
  'Mining and Smithing',
  'Potions',
  'Prayer Armour',
  'Prayer Materials',
  'Range Armour',
  'Range Weapons',
  'Runecrafting',
  'Runes, Spells, and Teleports',
  'Seeds',
  'Summoning Scrolls',
  'Tools and Containers',
  'Woodcutting product',
  'Pocket Items'
]

export const BASE = `https://cors-anywhere.herokuapp.com/`
export const BASE_URL = 'http://services.runescape.com/'
